[package]
name = "risk"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
domain = { path = "../domain" }
portfolio = { path = "../portfolio" }
serde.workspace = true
thiserror.workspace = true
